# Generated by Django 3.2.7 on 2025-12-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normal_user',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='normal_user',
            old_name='last_name',
            new_name='user_name',
        ),
    ]
