# Generated by Django 3.2.7 on 2025-12-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20251209_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normal_user',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='normal_user',
            old_name='user_name',
            new_name='username',
        ),
    ]
