# Generated by Django 3.2.7 on 2025-12-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20251209_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normal_user',
            old_name='profile_image',
            new_name='profile',
        ),
    ]
