# Generated by Django 3.2.7 on 2025-12-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_profile_image_normal_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
