# Generated by Django 3.2.7 on 2025-12-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_normal_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal_user',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
