# Generated by Django 3.2.7 on 2025-12-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_normal_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority_user',
            name='password',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
