# Generated by Django 3.2.7 on 2025-12-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_legaldumpinglocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldumpinglocation',
            name='location_type',
            field=models.CharField(blank=True, choices=[('bin', 'Garbage Bin'), ('recycling', 'Recycling Center'), ('transfer', 'Transfer Station'), ('hazardous', 'Hazardous Waste')], max_length=50, null=True),
        ),
    ]
