# Generated by Django 3.2.7 on 2025-12-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_legaldumpinglocation_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldumpinglocation',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.authority_user'),
        ),
    ]
