# Generated by Django 3.2.7 on 2026-01-07 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_legaldumpinglocation_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DumpingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('actor', models.CharField(blank=True, max_length=50)),
                ('dumping_video', models.FileField(upload_to='evidence/%Y/%m/%d/dumping/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.camera')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.legaldumpinglocation')),
            ],
        ),
        migrations.CreateModel(
            name='NumberPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence/%Y/%m/%d/plates/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plate_text', models.CharField(blank=True, max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='login.dumpingevent')),
            ],
        ),
    ]
