# Generated by Django 3.2.7 on 2026-01-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20260108_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumpingevent',
            name='location',
        ),
        migrations.AddField(
            model_name='dumpingevent',
            name='illegal_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
