# Generated by Django 3.2.7 on 2026-04-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20260114_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagereport',
            name='status',
            field=models.CharField(choices=[('under_investigation', 'Under Investigation'), ('action_taken', 'Action Taken'), ('action_not_taken', 'Action Not Taken')], default='under_investigation', max_length=50),
        ),
    ]
